# Generated by Django 4.2.3 on 2023-07-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='info',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='headlines',
            new_name='headline',
        ),
    ]
