# Generated by Django 4.2.3 on 2023-07-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_info_news_body_rename_headlines_news_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date_added',
            new_name='date',
        ),
    ]
