# Generated by Django 4.2.3 on 2023-07-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image_movie',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='url_of_movie',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year_added',
            new_name='year',
        ),
    ]
