# Generated by Django 4.2.3 on 2023-07-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchlist',
            new_name='watchAgain',
        ),
    ]
